task_runner: ray_local
cluster_name: ???

wandb:
  log: False
  log_artifact: True
  project: ???
  entity: ???
  code_dir: ./

cluster_hierarchy:
  cluster:
    - node

local_cache_path:
  node: ???

bart_path:
  node: /mnt/mri_libs/bart-0.6.00
